### ISSUE TITLE
Question about OAG download

### ISSUE THREAD

**Issue by jiaruHithub** [THUDM/OAG-BERT#4]
Hi, I find I cna't download hte OAG dataset via link{https://www.microsoft.com/en-us/research/project/open-academic-graph/}.
Will OAG still download?

**Comment by Xiao9905** [comment]
@jiaruHithub ,

You may try this backup: https://www.aminer.cn/open-academic-graph

**Comment by jiaruHithub** [comment]
> 

Thanks, but this url still can't open. It show that ```ERR_EMPTY_RESPONSE```.
Is there any other method?

**Comment by Xiao9905** [comment]
@jiaruHithub 

Try copy this link to your browser directly: https://www.aminer.cn/open-academic-graph

**Comment by jiaruHithub** [comment]
> https://www.aminer.cn/open-academic-graph

That's what I did, the home page can be open ,but if I click to download dataset like ```[mag_papers_0.zip]```(https://academicgraphv2.blob.core.windows.net/oag-v1/mag/mag_papers_0.zip), it show that ```DNS_PROBE_FINISHED_NXDOMAIN```

Can you download successfully?

**Comment by Xiao9905** [comment]
@zfjsail

**Comment by Xiao9905** [comment]
@jiaruHithub 

Hi, please try this version: https://www.aminer.cn/oag-2-1

**Comment by jiaruHithub** [comment]
> @jiaruHithub
> 
> Hi, please try this version: https://www.aminer.cn/oag-2-1

Thanks very much, it worked
