### ISSUE TITLE
Fine-tuning OAG-BERT

### ISSUE THREAD

**Issue by yuzhimanhua** [THUDM/OAG-BERT#5]
Hello,

Thank you for your great work and for releasing the model!

May I ask whether the CogDL package supports fine-tuning OAG-BERT (e.g., by adding one layer upon OAG-BERT to perform [CLS] classification or sequence labeling)? If we implement this additional layer in PyTorch, will the backward process update the parameters in OAG-BERT as well? Thanks!

**Comment by Xiao9905** [comment]
@yuzhimanhua Hi,

Yes, the OAG-BERT is implemented by original PyTorch, so you can regard it as any other language models from huggingface transformers in your usage.

**Comment by yuzhimanhua** [comment]
Got it. Thank you for the prompt response!
